package io.github.scave.lsp4a.model.document;

import java.net.URI;

/**
 * The class for storing a identifier of a text document
 * @author Scave
 */
public class TextDocumentIdentifier {

    /**
     * The specific identifier of a text document
     */
    public URI uri;

    public TextDocumentIdentifier() {
    }

    /**
     * Construct a text document identifier by uri
     * @param uri The uri generated by a file,asset or url and so on
     */
    public TextDocumentIdentifier(URI uri) {
        this.uri = uri;
    }
}
